# Generated by Django 5.2.4 on 2025-07-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='user_message',
            new_name='user_question',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='character',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='character_name',
            field=models.CharField(default='Mahatma Gandhi', max_length=100),
            preserve_default=False,
        ),
    ]
