# Generated by Django 5.2.4 on 2025-07-25 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_rename_user_message_chathistory_user_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='birth_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='death_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='famous_quotes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='historical_context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='major_achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='era',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='persona',
            field=models.TextField(blank=True),
        ),
    ]
